apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: u-assist-promise
spec:
  releaseName: u-assist-promise
  targetNamespace: platform
  values:
    datadog:
      env: prod
