{{- if .Values.customClaim.restrict }}
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: uassist-jwt-claims-validate
plugin: kong-plugin-sa-jwt-claims-validate
config:
  log_level: info
  option_expose_headers: false
  claims:
    "{{ .Values.customClaim.key }}": "{{ .Values.customClaim.value }}"
{{- end }}
