{{- if .Values.useElasticCacheFromSecrets }}
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: elastic-credential-promise
spec:
  backendType: secretsManager
  dataFrom:
    - uassist/elasticcluster
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: elastic-credential-promise
type: Opaque
stringData:
  cluster: {{ .Values.redis.cluster }}
  secret: {{ .Values.redis.secret }}
{{- end }}

