apiVersion: v1
kind: Service
metadata:
  name: u-assist-promise
  labels:
    {{- include "u-assist-promise.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3381
      targetPort: 3381
      protocol: TCP
  selector:
    {{- include "u-assist-promise.selectorLabels" . | nindent 4 }}
